name: lcbench-189906_prior-bad
api:
  name: lcbench
  prior: bad
  datadir: ${hydra:runtime.cwd}/data/yahpo-gym-data
  task_id: '189906'
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
prior_highest_fidelity_error: 0.8170135617256165
prior_lowest_error: 0.8170135617256165
best_10_error: 0.1518094539642334
best_25_error: 0.1518094539642334
best_50_error: 0.11257266998291016
best_90_error: 0.11257266998291016
best_100_error: 0.11257266998291016
