name: mfh3_good_prior-medium
epsilon: 0.125
api:
  name: mfh3_good
  prior: medium
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
prior_highest_fidelity_error: -3.859105735744569
prior_lowest_error: -3.859105735744569
best_10_error: -2.387332793243451
best_25_error: -3.5329301584153674
best_50_error: -3.606943119653449
best_90_error: -3.606943119653449
best_100_error: -3.606943119653449
optimum: -3.8627797869493365
