name: translatewmt_xformer_64_prior-at25
api:
  name: translatewmt_xformer_64
  prior: at25
  datadir: ${hydra:runtime.cwd}/data/pd1-data
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
prior_highest_fidelity_error: 0.3563116490840912
prior_lowest_error: 0.3563116490840912
best_10_error: 0.37780052423477173
best_25_error: 0.3563116490840912
best_50_error: 0.34561291337013245
best_90_error: 0.3624337911605835
best_100_error: 0.3602689206600189
